services:
  minio:
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_SERVER_URL: https://s3.stgy.jp

  mailpit:
    expose:
      - "8025"

  caddy:
    ports: !override
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.vps:/etc/caddy/Caddyfile:ro
