#!/usr/bin/env bash
set -euo pipefail

# ====== Embedded "production" config (baked into start.sh) ======
CFG_NODE_ENV=production
CFG_FRONTEND_ORIGIN=https://stgy.jp
CFG_BACKEND_PORT=3100
CFG_BACKEND_API_BASE_URL=https://stgy.jp/backend
CFG_BACKEND_API_PRIVATE_URL_LIST=http://127.0.0.1:3100

# PostgreSQL (native service on the host)
CFG_DB_HOST=127.0.0.1
CFG_DB_PORT=5432
CFG_DB_USER=admin
CFG_DB_PASS=stgystgy
CFG_DB_NAME=stgy

# MinIO (host:9000 directly; public delivery via Caddy)
CFG_S3_ENDPOINT=http://127.0.0.1:9000
CFG_S3_REGION=us-east-1
CFG_S3_KEY=admin
CFG_S3_SECRET=stgystgy
CFG_S3_FORCE_PATH_STYLE=true
CFG_S3_BUCKET_PREFIX=stgy
CFG_S3_PUBLIC_URL_PREFIX=https://s3.stgy.jp/{bucket}/

# Redis (native service on the host)
CFG_REDIS_HOST=127.0.0.1
CFG_REDIS_PORT=6379
CFG_REDIS_PASS=stgystgy

# Search (TTTS native service on the host)
CFG_SEARCH_API_BASE_URL=http://127.0.0.1:3200

# SMTP (Postfix on the same host; auth not required for localhost)
CFG_SMTP_HOST=127.0.0.1
CFG_SMTP_PORT=587

# Misc
CFG_MAIL_FROM=noreply@stgy.jp
CFG_ID_WORKER=0
CFG_OPENAI_API_KEY="${STGY_OPENAI_API_KEY:-}"
CFG_TEST_SIGNUP_CODE=
# =======================================================================

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OWNER="${DEPLOY_OWNER:-$(id -un)}"
GROUP="${DEPLOY_GROUP:-$(id -gn)}"
TARGET="${DEPLOY_TARGET:-$HOME/stgy-backend}"

echo "[backend] Building and staging artifacts..."
cd "$REPO_ROOT"

# Monorepo build (backend + shared package)
npm ci --workspaces --include-workspace-root
npm run packages:build
npm run backend:build

# Prepare target directory
mkdir -p "$TARGET"

# Install runtime assets
rsync -a --delete backend/dist/           "$TARGET/dist/"
rsync -a --delete backend/src/prompts/     "$TARGET/dist/prompts/"
rsync -a            backend/package.json  "$TARGET/backend.package.json"
rsync -a --delete node_modules/           "$TARGET/node_modules/"
rsync -a --delete packages/               "$TARGET/packages/"

# Sanity check for entrypoints
# We only need index.js (API) and oneWorker.js (All workers)
for f in index.js oneWorker.js ; do
  if [[ ! -f "$TARGET/dist/$f" ]]; then
    echo "[error] Missing '$TARGET/dist/$f' (did the backend build produce it?)"
    exit 1
  fi
done

# Generate start.sh (self-contained; baked config; supports start/stop/status/restart)
cat > "$TARGET/start.sh" <<'EOS'
#!/usr/bin/env bash
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$APP_DIR"
RUN_DIR="$APP_DIR/run"
LOG_DIR="$APP_DIR/logs"
STOP_REQUEST_FILE="$RUN_DIR/stop-requested"
SUPERVISOR_PID_FILE="$RUN_DIR/supervisor.pid"
mkdir -p "$RUN_DIR" "$LOG_DIR"

# ===== baked-in config (generated by deploy-backend.sh) =====
export NODE_ENV='__CFG_NODE_ENV__'
export STGY_FRONTEND_ORIGIN='__CFG_FRONTEND_ORIGIN__'
export STGY_BACKEND_PORT='__CFG_BACKEND_PORT__'
export STGY_BACKEND_API_BASE_URL='__CFG_BACKEND_API_BASE_URL__'
export STGY_BACKEND_API_PRIVATE_URL_LIST='__CFG_BACKEND_API_PRIVATE_URL_LIST__'
export PORT="${STGY_BACKEND_PORT}"

export STGY_DATABASE_HOST='__CFG_DB_HOST__'
export STGY_DATABASE_PORT='__CFG_DB_PORT__'
export STGY_DATABASE_USER='__CFG_DB_USER__'
export STGY_DATABASE_PASSWORD='__CFG_DB_PASS__'
export STGY_DATABASE_NAME='__CFG_DB_NAME__'

export STGY_STORAGE_DRIVER='s3'
export STGY_STORAGE_S3_ENDPOINT='__CFG_S3_ENDPOINT__'
export STGY_STORAGE_S3_REGION='__CFG_S3_REGION__'
export STGY_STORAGE_S3_ACCESS_KEY_ID='__CFG_S3_KEY__'
export STGY_STORAGE_S3_SECRET_ACCESS_KEY='__CFG_S3_SECRET__'
export STGY_STORAGE_S3_FORCE_PATH_STYLE='__CFG_S3_FORCE_PATH_STYLE__'
export STGY_STORAGE_S3_BUCKET_PREFIX='__CFG_S3_BUCKET_PREFIX__'
export STGY_STORAGE_S3_PUBLIC_URL_PREFIX='__CFG_S3_PUBLIC_URL_PREFIX__'

export STGY_REDIS_HOST='__CFG_REDIS_HOST__'
export STGY_REDIS_PORT='__CFG_REDIS_PORT__'
export STGY_REDIS_PASSWORD='__CFG_REDIS_PASS__'

export STGY_SEARCH_API_BASE_URL='__CFG_SEARCH_API_BASE_URL__'

export STGY_SMTP_HOST='__CFG_SMTP_HOST__'
export STGY_SMTP_PORT='__CFG_SMTP_PORT__'

export STGY_MAIL_SENDER_ADDRESS='__CFG_MAIL_FROM__'
export STGY_ID_ISSUE_WORKER_ID='__CFG_ID_WORKER__'
export STGY_OPENAI_API_KEY='__CFG_OPENAI_API_KEY__'
export STGY_TEST_SIGNUP_CODE='__CFG_TEST_SIGNUP_CODE__'
# ===========================================================

NODE_BIN="$(command -v node || true)"
if [[ -z "$NODE_BIN" ]]; then
  echo "[error] 'node' not found in PATH"
  exit 1
fi

pidfile() { echo "$RUN_DIR/$1.pid"; }
expected_entry() {
  case "$1" in
    backend) echo "$APP_DIR/dist/index.js" ;;
    oneworker) echo "$APP_DIR/dist/oneWorker.js" ;;
    *) return 1 ;;
  esac
}
process_start_time() {
  local pid="$1" stat
  stat="$(cat "/proc/$pid/stat" 2>/dev/null)" || return 1
  local -a fields
  read -r -a fields <<<"${stat##*) }"
  [[ ${#fields[@]} -ge 20 ]] || return 1
  printf '%s\n' "${fields[19]}"
}
is_running() {
  local name="$1" pidfile_path; pidfile_path="$(pidfile "$name")"
  [[ -f "$pidfile_path" ]] || return 1

  local pid recorded_start extra
  read -r pid recorded_start extra <"$pidfile_path" || return 1
  [[ "$pid" =~ ^[0-9]+$ && "$recorded_start" =~ ^[0-9]+$ && -z "${extra:-}" ]] || return 1
  [[ -d "/proc/$pid" ]] || return 1

  local current_start
  current_start="$(process_start_time "$pid")" || return 1
  [[ "$current_start" == "$recorded_start" ]] || return 1

  local entry
  entry="$(expected_entry "$name")" || return 1
  grep -Fzxq -- "$NODE_BIN" "/proc/$pid/cmdline" 2>/dev/null &&
    grep -Fzxq -- "$entry" "/proc/$pid/cmdline" 2>/dev/null
}

start_one() {
  local name="$1" entry="$2"
  local log="$LOG_DIR/$name.log" pf; pf="$(pidfile "$name")"
  if is_running "$name"; then
    local pid; read -r pid _ <"$pf"
    echo "[$name] already running (pid $pid)"
    return 0
  fi
  echo "[$name] starting..."
  nohup "$NODE_BIN" "$entry" >>"$log" 2>&1 &
  local pid=$! start_time
  start_time="$(process_start_time "$pid" 2>/dev/null || true)"
  if [[ ! "$start_time" =~ ^[0-9]+$ ]]; then
    echo "[$name] failed to record process identity; see $log"
    return 1
  fi
  printf '%s %s\n' "$pid" "$start_time" >"$pf"
  sleep 0.2
  if is_running "$name"; then
    echo "[$name] started (pid $pid)"
  else
    echo "[$name] failed to start; see $log"
    return 1
  fi
}

stop_one() {
  local name="$1" pf; pf="$(pidfile "$name")"
  if ! is_running "$name"; then
    rm -f "$pf"
    echo "[$name] not running"
    return 0
  fi
  local pid; read -r pid _ <"$pf"
  echo "[$name] stopping (pid $pid)..."
  kill -TERM "$pid" 2>/dev/null || true

  # wait up to 10s, then KILL
  for _ in {1..20}; do
    if ! is_running "$name"; then
      break
    fi
    sleep 0.5
  done
  if is_running "$name"; then
    echo "[$name] still alive; killing..."
    kill -KILL "$pid" 2>/dev/null || true
  fi
  rm -f "$pf"
  echo "[$name] stopped"
}

status_one() {
  local name="$1" pf; pf="$(pidfile "$name")"
  if is_running "$name"; then
    local pid; read -r pid _ <"$pf"
    echo "[$name] RUNNING (pid $pid)"
  else
    echo "[$name] STOPPED"
    return 3
  fi
}

start_all() {
  start_one "backend" "$(expected_entry backend)"
  if ! start_one "oneworker" "$(expected_entry oneworker)"; then
    stop_one "backend"
    return 1
  fi
}

stop_all() {
  stop_one "oneworker"
  stop_one "backend"
}

status_all() {
  local status=0
  status_one "backend" || status=3
  status_one "oneworker" || status=3
  return "$status"
}

end_supervision() {
  rm -f "$SUPERVISOR_PID_FILE" "$STOP_REQUEST_FILE"
}

wait_for_supervisor() {
  [[ -f "$SUPERVISOR_PID_FILE" ]] || return 0
  local pid recorded_start extra current_start
  read -r pid recorded_start extra <"$SUPERVISOR_PID_FILE" || true
  if [[ ! "$pid" =~ ^[0-9]+$ ]] ||
     [[ ! "$recorded_start" =~ ^[0-9]+$ ]] ||
     [[ -n "${extra:-}" ]] ||
     [[ "$pid" == "$$" ]]; then
    rm -f "$SUPERVISOR_PID_FILE"
    return 0
  fi
  current_start="$(process_start_time "$pid" 2>/dev/null || true)"
  if [[ "$current_start" != "$recorded_start" ]]; then
    rm -f "$SUPERVISOR_PID_FILE"
    return 0
  fi
  for _ in {1..30}; do
    if ! kill -0 "$pid" 2>/dev/null; then
      rm -f "$SUPERVISOR_PID_FILE"
      return 0
    fi
    sleep 0.1
  done
  echo "[supervisor] did not exit after stop request" >&2
  return 1
}

request_stop() {
  : >"$STOP_REQUEST_FILE"
  stop_all
  wait_for_supervisor
  if [[ ! -f "$SUPERVISOR_PID_FILE" ]]; then
    rm -f "$STOP_REQUEST_FILE"
  fi
}

supervisor_shutdown() {
  echo "[supervisor] SIGTERM received"
  : >"$STOP_REQUEST_FILE"
  stop_all
  end_supervision
  exit 0
}

# If launched without args: run in foreground & supervise children.
case "${1:-start}" in
  start)
    rm -f "$STOP_REQUEST_FILE"
    supervisor_start_time="$(process_start_time "$$")"
    printf '%s %s\n' "$$" "$supervisor_start_time" >"$SUPERVISOR_PID_FILE"
    trap supervisor_shutdown TERM INT
    if ! start_all; then
      end_supervision
      exit 1
    fi
    # Wait until any child exits; then stop the rest and propagate failure.
    while true; do
      if ! is_running "backend" || ! is_running "oneworker"; then
        if [[ -f "$STOP_REQUEST_FILE" ]]; then
          echo "[supervisor] stop requested; stopping..."
          stop_all
          end_supervision
          exit 0
        fi
        echo "[supervisor] a child process exited; stopping the others..."
        stop_all
        end_supervision
        exit 1
      fi
      sleep 1
    done
    ;;
  stop)
    request_stop
    ;;
  restart)
    request_stop
    exec "$0" start
    ;;
  status)
    status_all
    ;;
  *)
    echo "Usage: $0 [start|stop|restart|status]"
    exit 2
    ;;
esac
EOS

# Inject baked config values without interpreting sed replacement characters.
# The template places every placeholder inside a single-quoted shell string, so
# only embedded single quotes need shell escaping.
TARGET_START_SH="$TARGET/start.sh" \
INJECT_CFG_NODE_ENV="$CFG_NODE_ENV" \
INJECT_CFG_FRONTEND_ORIGIN="$CFG_FRONTEND_ORIGIN" \
INJECT_CFG_BACKEND_PORT="$CFG_BACKEND_PORT" \
INJECT_CFG_BACKEND_API_BASE_URL="$CFG_BACKEND_API_BASE_URL" \
INJECT_CFG_BACKEND_API_PRIVATE_URL_LIST="$CFG_BACKEND_API_PRIVATE_URL_LIST" \
INJECT_CFG_DB_HOST="$CFG_DB_HOST" \
INJECT_CFG_DB_PORT="$CFG_DB_PORT" \
INJECT_CFG_DB_USER="$CFG_DB_USER" \
INJECT_CFG_DB_PASS="$CFG_DB_PASS" \
INJECT_CFG_DB_NAME="$CFG_DB_NAME" \
INJECT_CFG_S3_ENDPOINT="$CFG_S3_ENDPOINT" \
INJECT_CFG_S3_REGION="$CFG_S3_REGION" \
INJECT_CFG_S3_KEY="$CFG_S3_KEY" \
INJECT_CFG_S3_SECRET="$CFG_S3_SECRET" \
INJECT_CFG_S3_FORCE_PATH_STYLE="$CFG_S3_FORCE_PATH_STYLE" \
INJECT_CFG_S3_BUCKET_PREFIX="$CFG_S3_BUCKET_PREFIX" \
INJECT_CFG_S3_PUBLIC_URL_PREFIX="$CFG_S3_PUBLIC_URL_PREFIX" \
INJECT_CFG_REDIS_HOST="$CFG_REDIS_HOST" \
INJECT_CFG_REDIS_PORT="$CFG_REDIS_PORT" \
INJECT_CFG_REDIS_PASS="$CFG_REDIS_PASS" \
INJECT_CFG_SEARCH_API_BASE_URL="$CFG_SEARCH_API_BASE_URL" \
INJECT_CFG_SMTP_HOST="$CFG_SMTP_HOST" \
INJECT_CFG_SMTP_PORT="$CFG_SMTP_PORT" \
INJECT_CFG_MAIL_FROM="$CFG_MAIL_FROM" \
INJECT_CFG_ID_WORKER="$CFG_ID_WORKER" \
INJECT_CFG_OPENAI_API_KEY="$CFG_OPENAI_API_KEY" \
INJECT_CFG_TEST_SIGNUP_CODE="$CFG_TEST_SIGNUP_CODE" \
node <<'NODE'
const fs = require('fs');

const path = process.env.TARGET_START_SH;
let text = fs.readFileSync(path, 'utf8');

const replacements = {
  __CFG_NODE_ENV__: process.env.INJECT_CFG_NODE_ENV,
  __CFG_FRONTEND_ORIGIN__: process.env.INJECT_CFG_FRONTEND_ORIGIN,
  __CFG_BACKEND_PORT__: process.env.INJECT_CFG_BACKEND_PORT,
  __CFG_BACKEND_API_BASE_URL__: process.env.INJECT_CFG_BACKEND_API_BASE_URL,
  __CFG_BACKEND_API_PRIVATE_URL_LIST__: process.env.INJECT_CFG_BACKEND_API_PRIVATE_URL_LIST,
  __CFG_DB_HOST__: process.env.INJECT_CFG_DB_HOST,
  __CFG_DB_PORT__: process.env.INJECT_CFG_DB_PORT,
  __CFG_DB_USER__: process.env.INJECT_CFG_DB_USER,
  __CFG_DB_PASS__: process.env.INJECT_CFG_DB_PASS,
  __CFG_DB_NAME__: process.env.INJECT_CFG_DB_NAME,
  __CFG_S3_ENDPOINT__: process.env.INJECT_CFG_S3_ENDPOINT,
  __CFG_S3_REGION__: process.env.INJECT_CFG_S3_REGION,
  __CFG_S3_KEY__: process.env.INJECT_CFG_S3_KEY,
  __CFG_S3_SECRET__: process.env.INJECT_CFG_S3_SECRET,
  __CFG_S3_FORCE_PATH_STYLE__: process.env.INJECT_CFG_S3_FORCE_PATH_STYLE,
  __CFG_S3_BUCKET_PREFIX__: process.env.INJECT_CFG_S3_BUCKET_PREFIX,
  __CFG_S3_PUBLIC_URL_PREFIX__: process.env.INJECT_CFG_S3_PUBLIC_URL_PREFIX,
  __CFG_REDIS_HOST__: process.env.INJECT_CFG_REDIS_HOST,
  __CFG_REDIS_PORT__: process.env.INJECT_CFG_REDIS_PORT,
  __CFG_REDIS_PASS__: process.env.INJECT_CFG_REDIS_PASS,
  __CFG_SEARCH_API_BASE_URL__: process.env.INJECT_CFG_SEARCH_API_BASE_URL,
  __CFG_SMTP_HOST__: process.env.INJECT_CFG_SMTP_HOST,
  __CFG_SMTP_PORT__: process.env.INJECT_CFG_SMTP_PORT,
  __CFG_MAIL_FROM__: process.env.INJECT_CFG_MAIL_FROM,
  __CFG_ID_WORKER__: process.env.INJECT_CFG_ID_WORKER,
  __CFG_OPENAI_API_KEY__: process.env.INJECT_CFG_OPENAI_API_KEY,
  __CFG_TEST_SIGNUP_CODE__: process.env.INJECT_CFG_TEST_SIGNUP_CODE,
};

const escapeSingleQuotedShellContent = (value) =>
  String(value ?? '').replace(/'/g, "'\"'\"'");

for (const [placeholder, value] of Object.entries(replacements)) {
  if (!text.includes(placeholder)) {
    throw new Error(`placeholder not found: ${placeholder}`);
  }
  text = text.split(placeholder).join(escapeSingleQuotedShellContent(value));
}

fs.writeFileSync(path, text);
NODE

chmod 700 "$TARGET/start.sh"

# Ownership (best-effort if changing user/group)
if [[ "$(id -un)" != "$OWNER" ]] || [[ "$(id -gn)" != "$GROUP" ]]; then
  if command -v sudo >/dev/null 2>&1; then
    sudo chown -R "$OWNER:$GROUP" "$TARGET"
  else
    echo "[warn] Skipping chown (sudo not available): expected $OWNER:$GROUP -> $TARGET"
  fi
fi

echo "[backend] Deployment completed: $TARGET"
echo "  To run in foreground (recommended for systemd): $TARGET/start.sh"
echo "  To stop:                                      $TARGET/start.sh stop"
echo "  Logs: $TARGET/logs/*.log"
