#!/usr/bin/env bash
set -euo pipefail

# ====== Embedded "production" config (baked into start.sh) ======
CFG_NODE_ENV=production
CFG_SEARCH_PORT=3200
# Data directory name relative to the installation directory
CFG_SEARCH_INDEX_DIR_NAME=data
CFG_ENABLE_KUROMOJI=true
# =======================================================================

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OWNER="${DEPLOY_OWNER:-$(id -un)}"
GROUP="${DEPLOY_GROUP:-$(id -gn)}"
TARGET="${DEPLOY_TARGET:-$HOME/stgy-ttts}"

echo "[ttts] Building and staging artifacts..."
cd "$REPO_ROOT"

# Monorepo build (target ttts workspace)
npm ci --workspaces --include-workspace-root
npm run build --workspace ttts

# Prepare target directory
mkdir -p "$TARGET"

# Install runtime assets
rsync -a --delete ttts/dist/              "$TARGET/dist/"
rsync -a            ttts/package.json     "$TARGET/ttts.package.json"
rsync -a --delete node_modules/           "$TARGET/node_modules/"

# Sanity check for entrypoints
if [[ ! -f "$TARGET/dist/index.js" ]]; then
  echo "[error] Missing '$TARGET/dist/index.js' (did the ttts build produce it?)"
  exit 1
fi

# Generate start.sh (self-contained; baked config; supports start/stop/status/restart)
cat > "$TARGET/start.sh" <<'EOS'
#!/usr/bin/env bash
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$APP_DIR"
RUN_DIR="$APP_DIR/run"
LOG_DIR="$APP_DIR/logs"
DATA_DIR="$APP_DIR/__CFG_SEARCH_INDEX_DIR_NAME__"
STOP_REQUEST_FILE="$RUN_DIR/stop-requested"
SUPERVISOR_PID_FILE="$RUN_DIR/supervisor.pid"

mkdir -p "$RUN_DIR" "$LOG_DIR" "$DATA_DIR"

# ===== baked-in config (generated by deploy-ttts.sh) =====
export NODE_ENV='__CFG_NODE_ENV__'
export STGY_SEARCH_PORT='__CFG_SEARCH_PORT__'
export STGY_SEARCH_INDEX_DIR="$DATA_DIR"
export STGY_SEARCH_ENABLE_KUROMOJI='__CFG_ENABLE_KUROMOJI__'
# ===========================================================

NODE_BIN="$(command -v node || true)"
if [[ -z "$NODE_BIN" ]]; then
  echo "[error] 'node' not found in PATH"
  exit 1
fi

pidfile() { echo "$RUN_DIR/$1.pid"; }
expected_entry() { echo "$APP_DIR/dist/index.js"; }
process_start_time() {
  local pid="$1" stat
  stat="$(cat "/proc/$pid/stat" 2>/dev/null)" || return 1
  local -a fields
  read -r -a fields <<<"${stat##*) }"
  [[ ${#fields[@]} -ge 20 ]] || return 1
  printf '%s\n' "${fields[19]}"
}
is_running() {
  local name="$1" pidfile_path; pidfile_path="$(pidfile "$name")"
  [[ -f "$pidfile_path" ]] || return 1

  local pid recorded_start extra
  read -r pid recorded_start extra <"$pidfile_path" || return 1
  [[ "$pid" =~ ^[0-9]+$ && "$recorded_start" =~ ^[0-9]+$ && -z "${extra:-}" ]] || return 1
  [[ -d "/proc/$pid" ]] || return 1

  local current_start
  current_start="$(process_start_time "$pid")" || return 1
  [[ "$current_start" == "$recorded_start" ]] || return 1

  local entry
  entry="$(expected_entry)"
  grep -Fzxq -- "$NODE_BIN" "/proc/$pid/cmdline" 2>/dev/null &&
    grep -Fzxq -- "$entry" "/proc/$pid/cmdline" 2>/dev/null
}

start_one() {
  local name="$1" entry="$2"
  local log="$LOG_DIR/$name.log" pf; pf="$(pidfile "$name")"
  if is_running "$name"; then
    local pid; read -r pid _ <"$pf"
    echo "[$name] already running (pid $pid)"
    return 0
  fi
  echo "[$name] starting..."
  nohup "$NODE_BIN" "$entry" >>"$log" 2>&1 &
  local pid=$! start_time
  start_time="$(process_start_time "$pid" 2>/dev/null || true)"
  if [[ ! "$start_time" =~ ^[0-9]+$ ]]; then
    echo "[$name] failed to record process identity; see $log"
    return 1
  fi
  printf '%s %s\n' "$pid" "$start_time" >"$pf"
  sleep 0.2
  if is_running "$name"; then
    echo "[$name] started (pid $pid)"
  else
    echo "[$name] failed to start; see $log"
    return 1
  fi
}

stop_one() {
  local name="$1" pf; pf="$(pidfile "$name")"
  if ! is_running "$name"; then
    rm -f "$pf"
    echo "[$name] not running"
    return 0
  fi
  local pid; read -r pid _ <"$pf"
  echo "[$name] stopping (pid $pid)..."
  kill -TERM "$pid" 2>/dev/null || true

  # wait up to 10s, then KILL
  for _ in {1..20}; do
    if ! is_running "$name"; then
      break
    fi
    sleep 0.5
  done
  if is_running "$name"; then
    echo "[$name] still alive; killing..."
    kill -KILL "$pid" 2>/dev/null || true
  fi
  rm -f "$pf"
  echo "[$name] stopped"
}

status_one() {
  local name="$1" pf; pf="$(pidfile "$name")"
  if is_running "$name"; then
    local pid; read -r pid _ <"$pf"
    echo "[$name] RUNNING (pid $pid)"
  else
    echo "[$name] STOPPED"
    return 3
  fi
}

start_all() {
  start_one "ttts" "$(expected_entry)"
}

stop_all() {
  stop_one "ttts"
}

status_all() {
  status_one "ttts"
}

end_supervision() {
  rm -f "$SUPERVISOR_PID_FILE" "$STOP_REQUEST_FILE"
}

wait_for_supervisor() {
  [[ -f "$SUPERVISOR_PID_FILE" ]] || return 0
  local pid recorded_start extra current_start
  read -r pid recorded_start extra <"$SUPERVISOR_PID_FILE" || true
  if [[ ! "$pid" =~ ^[0-9]+$ ]] ||
     [[ ! "$recorded_start" =~ ^[0-9]+$ ]] ||
     [[ -n "${extra:-}" ]] ||
     [[ "$pid" == "$$" ]]; then
    rm -f "$SUPERVISOR_PID_FILE"
    return 0
  fi
  current_start="$(process_start_time "$pid" 2>/dev/null || true)"
  if [[ "$current_start" != "$recorded_start" ]]; then
    rm -f "$SUPERVISOR_PID_FILE"
    return 0
  fi
  for _ in {1..30}; do
    if ! kill -0 "$pid" 2>/dev/null; then
      rm -f "$SUPERVISOR_PID_FILE"
      return 0
    fi
    sleep 0.1
  done
  echo "[supervisor] did not exit after stop request" >&2
  return 1
}

request_stop() {
  : >"$STOP_REQUEST_FILE"
  stop_all
  wait_for_supervisor
  if [[ ! -f "$SUPERVISOR_PID_FILE" ]]; then
    rm -f "$STOP_REQUEST_FILE"
  fi
}

supervisor_shutdown() {
  echo "[supervisor] SIGTERM received"
  : >"$STOP_REQUEST_FILE"
  stop_all
  end_supervision
  exit 0
}

# If launched without args: run in foreground & supervise children.
case "${1:-start}" in
  start)
    rm -f "$STOP_REQUEST_FILE"
    supervisor_start_time="$(process_start_time "$$")"
    printf '%s %s\n' "$$" "$supervisor_start_time" >"$SUPERVISOR_PID_FILE"
    trap supervisor_shutdown TERM INT
    if ! start_all; then
      end_supervision
      exit 1
    fi
    # Wait until child exits
    while true; do
      if ! is_running "ttts"; then
        if [[ -f "$STOP_REQUEST_FILE" ]]; then
          echo "[supervisor] stop requested; stopping..."
          stop_all
          end_supervision
          exit 0
        fi
        echo "[supervisor] ttts process exited; stopping..."
        stop_all
        end_supervision
        exit 1
      fi
      sleep 1
    done
    ;;
  stop)
    request_stop
    ;;
  restart)
    request_stop
    exec "$0" start
    ;;
  status)
    status_all
    ;;
  *)
    echo "Usage: $0 [start|stop|restart|status]"
    exit 2
    ;;
esac
EOS

# Inject baked config values safely
sed -i \
  -e "s#__CFG_NODE_ENV__#${CFG_NODE_ENV}#g" \
  -e "s#__CFG_SEARCH_PORT__#${CFG_SEARCH_PORT}#g" \
  -e "s#__CFG_SEARCH_INDEX_DIR_NAME__#${CFG_SEARCH_INDEX_DIR_NAME}#g" \
  -e "s#__CFG_ENABLE_KUROMOJI__#${CFG_ENABLE_KUROMOJI}#g" \
  "$TARGET/start.sh"

chmod +x "$TARGET/start.sh"

# Ownership (best-effort if changing user/group)
if [[ "$(id -un)" != "$OWNER" ]] || [[ "$(id -gn)" != "$GROUP" ]]; then
  if command -v sudo >/dev/null 2>&1; then
    sudo chown -R "$OWNER:$GROUP" "$TARGET"
  else
    echo "[warn] Skipping chown (sudo not available): expected $OWNER:$GROUP -> $TARGET"
  fi
fi

echo "[ttts] Deployment completed: $TARGET"
echo "  To run in foreground (recommended for systemd): $TARGET/start.sh"
echo "  To stop:                                      $TARGET/start.sh stop"
echo "  Logs: $TARGET/logs/*.log"
